# Generated by Django 3.2.12 on 2022-03-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=250)),
                ('imag', models.ImageField(upload_to='pics')),
                ('detail', models.TextField()),
            ],
        ),
    ]
