# Generated by Django 3.2.12 on 2022-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0003_auto_20220303_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='imag',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
